apiVersion: v2
name: monitoring
description: A wrapper chart for Monitoring (Grafana stack)
type: application
version: 1.0.0
appVersion: "1.0.6"
dependencies:
  - name: k8s-monitoring
    version: 1.0.6
    repository: https://grafana.github.io/helm-charts
