apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-control-plane
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sangtd05/gitops-repo.git
    targetRevision: main
    path: resources/argocd-control-plane
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
