# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: monitoring
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/sangtd05/gitops-repo.git
#     targetRevision: main
#     path: resources/monitoring

#   destination:
#     server: https://kubernetes.default.svc
#     namespace: monitoring

#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
#       - ServerSideApply=true
#       - SkipDryRunOnMissingResource=true
