apiVersion: v2
name: headlamp
description: A wrapper chart for Headlamp
type: application
version: 1.0.0
appVersion: "0.26.0"
dependencies:
  - name: headlamp
    version: 0.26.0
    repository: https://kubernetes-sigs.github.io/headlamp/
